#ifndef ENUMS_H
#define ENUMS_H

typedef enum
{
	ROUND_FREEZE, ROUND_REGULAR, ROUND_AFTER
}
RoundStatus;

typedef enum 
{
	B_BEGIN_PLANT, B_ABORT_PLANT, B_COMPLETE_PLANT, 
	B_BEGIN_DEFUSE, B_ABORT_DEFUSE, B_COMPLETE_DEFUSE,
	B_PICK_UP, B_DROP, B_EXPLODE
}
BombEvent;

typedef enum
{
	MOLOTOV_START, MOLOTOV_EXPIRE, MOLOTOV_EXTINGUISH, SMOKE_DETONATE, SMOKE_EXPIRED,
	FLASH_DETONATE, HE_DETONATE, DECOY_START, DECOY_FIRE, DECOY_DETONATE
}
GrenadeEvent;

typedef enum
{
	PLAYER_DEFAULT, PLAYER_PLANTING, PLAYER_DEFUSING, PLAYER_FIRING
}
PlayerStatus;

#endif